# Generated by Django 5.0.6 on 2024-05-18 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiUsers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='status',
            field=models.CharField(default='pending', max_length=30),
        ),
    ]
